apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argoproj
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform-demo
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 2.37.5
    chart: argo-rollouts
    helm:
      parameters:
        - name: dashboard.ingress.enabled
          value: "true"
        - name: dashboard.enabled
          value: "true"
  destination:
    namespace: argoproj
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
