apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argoproj
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: vault
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.5
    chart: external-dns
    helm:
      values: "domainFilters:\n  - synera.com.br\nprovider: \n  name: cloudflare\nenv:\n- name: CF_API_TOKEN\n  value: __CF_TOKEN__\n"
  sources: []
  project: platform-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
