apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argoproj
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform-demo
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.11.2
    chart: ingress-nginx
    helm:
      values: |
        service:
          annotations: 
            service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
            service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: 31
  destination:
    namespace: ingress-controller
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
