apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argoproj
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: ""
    namespace: "nginx-controller"
    server: https://kubernetes.default.svc
  project: platform-demo
  source:
    path: ""
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: 4.11.2
    chart: ingress-nginx/ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 2m0s
        factor: 2

