apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: ingress-controller
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.11.2
    chart: ingress-nginx
    helm:
      parameters:
      - name: installCRDs
        value: "true"
  sources: []
  project: platform-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
