apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argoproj
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.4.7
    chart: grafana
  sources: []
  project: platform-demo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
