apiVersion: v1
kind: Secret
metadata:
  name: argoproj
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://argoproj.github.io/argo-helm
  name: argoproj
  type: helm
