---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
stringData:
  url: https://charts.external-secrets.io
  name: external-secrets
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: hashicorp
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
stringData:
  url: https://helm.releases.hashicorp.com
  name: hashicorp
  type: helm
