apiVersion: v1
kind: Secret
metadata:
  name: external-secrets
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
stringData:
  url: https://charts.external-secrets.io
  name: external-secrets
  type: helm
