apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://grafana.github.io/helm-charts
  name: grafana
  type: helm


 