apiVersion: v1
kind: Secret
metadata:
  name: ingress
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
stringData:
  url: https://kubernetes.github.io/ingress-nginx
  name: ingress
  type: helm
