apiVersion: v1
kind: Secret
metadata:
  name: opencost
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://opencost.github.io/opencost-helm-chart
  name: opencost
  type: helm
