apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community
  namespace: argoproj
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  url: https://prometheus-community.github.io/helm-charts
  name: prometheus-community
  type: helm
