apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argoproj
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform-demo
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 25.26.0
    chart: prometheus
    helm:
      values: |
        service:
          annotations: 
            service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
            service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: 31
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
