apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-demo
  namespace: platform-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterResourceWhitelis:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://argoproj.github.io/argo-helm'
