apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-demo
  namespace: argoproj
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://argoproj.github.io/argo-helm'
  - 'https://kubernetes.github.io/ingress-nginx'
