apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-demo
  namespace: argoproj
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
    name: in-cluster
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://argoproj.github.io/argo-helm'
  - 'https://kubernetes.github.io/ingress-nginx'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  - 'https://charts.external-secrets.io'
  - 'https://helm.releases.hashicorp.com'
  - 'https://kubernetes-sigs.github.io/external-dns'
