name: hashicorp-vault
run-name: Implement Hashicorp vault

on:
  workflow_call:
    inputs:
      kube_config:
        required: true
        type: string

env:
  ACTION: apply
  CLOUDFLARE_DNS_TOKEN: ${{ secrets.CLOUDFLARE_DNS_TOKEN }}
  CLOUDFLARE_ACCOUNT: ${{ secrets.CLOUDFLARE_ACCOUNT }}

jobs:
  vault:
    runs-on: 'ubuntu-latest'
    outputs:
      kube_config: ${{ inputs.kube-config }}
      vault_root_token: ${{ steps.unseal.outputs.root_token }}
    name: Enable Hashicorp vault
    permissions: 
      contents: read

    steps:
    - uses: actions/checkout@v1
    
    - name: Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo ${{ inputs.kube_config }}|base64 -d > ~/.kube/config

    - name: 
      id: unseal
      run: echo "root_token=$(echo ${{vars.VAULT_TOKEN}})" >> $GITHUB_OUTPUT

    - name: vault login
      run: |
        kubectl -n vault exec hashicorp-vault-0 -- vault login token=${{ vars.VAULT_TOKEN }}

    - name: Remove kubeconfig
      run: |
          rm -rf ~/.kube

        