name: vault-kubernetes
run-name: Vault resources in Kubernetes CI

on:
  workflow_call:
    inputs:
      kube_config:
        required: true
        type: string


env:
  kube_production: kttps://production-kubernetes.default.svc:443
  kube_development: kttps://development-kubernetes.default.svc:443
  ACTION: apply
  ARGOCD_RELEASE_NAME: argocd
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  CLOUDFLARE_DNS_TOKEN: ${{ secrets.CLOUDFLARE_DNS_TOKEN }}
  CLOUDFLARE_ACCOUNT: ${{ secrets.CLOUDFLARE_ACCOUNT }}

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    outputs:
      kube_config: ${{ inputs.kube_config }}
    name: Deployment by GitOps
    permissions: 
      contents: read
    steps:
    - uses: actions/checkout@v1
    
    - name: Action status
      run: echo ok
              
