name: deployment-kubernetes
run-name: Deployment resources in Kubernetes CI

on:
  workflow_call:
    inputs:
      kube-config:
        required: true
        type: string
      environment:
        required: true
        type: string  

env:
  kube_production: kttps://production-kubernetes.default.svc:443
  kube_development: kttps://development-kubernetes.default.svc:443
  ACTION: destroy

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    if: ${{ github.env.ACTION }} == 'apply'

    steps:
    - uses: actions/checkout@v1

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.13.0
        kubeconfig: ${{ inputs.kube-config }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        kubeconfig: ${{ inputs.kube-config }}
      env:
        CR_TOKEN: "${{ github.token }}"

    - name: Action status
      run: echo ${{ inputs.kube-config }}

    - name: Add dependency chart repos
      run: |
        helm repo add argo https://argoproj.github.io/argo-helm

    - name: Search argocd chart
      run: |
          helm search repo argo

    - name: Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo ${{ inputs.kube-config }}|base64 -d > ~/.kube/config

        # helm upgrade --install --values ./deployment/helm/argocd/values.yaml argocd argo/argo-cd --create-namespace --namespace argoproj 
        # helm uninstall argocd --namespace argoproj 
    - name: Install argocd chart
      if: ${{ env.ACTION }} == 'apply'
      run: |
        helm upgrade --install --values ./deployment/helm/argocd/values.yaml argocd argo/argo-cd --create-namespace --namespace argoproj 
        
    - name: Remove kubeconfig
      if: always()
      run: |
            rm -rf ~/.kube
