name: install-argocd
run-name: Install ArgoCD in kubernetes cluster

on:
  push:
    branches: [ "main", "develop", "production"]
  pull_request:
    branches: [ "main", "develop", "production"]

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ACTION: destroy

jobs:
  argocd:
    name: 'ArgoCD'
    runs-on: ubuntu-latest
    outputs:
      kube_config: ${{ steps.aks_cluster_name.outputs.CONFIG }}
      env: ${{ steps.environment.outputs.ENV }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo ${{ inputs.kube-config }}|base64 -d > ~/.kube/config
      - uses: actions/checkout@v3
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm list
          # kubeconfig: '${{ secrets.KUBECONFIG }}'
          overrule_existing_kubeconfig: "true"
      - name: remove Kubeconfig
        run: |
            rm -rf ~/.kube
